### ISSUE TITLE
Section 'Build Your Own Kernel' has a failed link.b

### ISSUE THREAD

**Issue by liubogithub** [hyperhq/book#21]
FYI, docs.hypercontainer.io/get_started/install/build.md

"You can find related configuration items in the config file."

There is a link for 'the config file', but it fails somehow.

**Comment by gnawux** [comment]
hi @liubogithub , we will update the document. And you can find the kernel config here: https://github.com/hyperhq/hyperstart/blob/master/build/kernel_config

**Comment by gnawux** [comment]
#22 fixed the link. 

I did not understand the issue well in the previous reply, but it works anyway. Thank you for report.

**Comment by gnawux** [comment]
The page has been updated, close this issue.

**Comment by liubogithub** [comment]
Cool, thanks for the quick fix
